import { ArrowUpRight, MonitorCog } from 'lucide-react'

const team = [
  ['Alex Hodo, MBA', 'CEO of Overdrive Accounting', 'Specializing in accounting and fractional CFO services for businesses. 15 years of experience providing strategic financial leadership, forecasting, cash-flow management, and business advisory services. Trusted advisor to business owners and leadership teams, focused on informed decision-making and sustainable growth. Serves on nearly 20 boards, with extensive experience in financial oversight, governance, and strategic planning.', 'https://overdriveaccountingservices.com/wp-content/uploads/2024/06/AlexHodo.jpg'],
  ['Wanda Nagovich, EA', 'Senior Managing Accountant', '25 years of experience in accounting, tax, payroll, consulting, and business advisory services. Nearly 20 years of controller experience, overseeing financial teams and managing financial reporting, reconciliations, budgeting, cash flow, and day-to-day accounting operations. Enrolled Agent authorized to represent businesses before the IRS and state tax authorities, with expertise in tax matters, compliance, and representation.', 'https://overdriveaccountingservices.com/wp-content/uploads/2024/06/Wanda2.jpg'],
  ['Karla Gonzalez', 'Senior Bookkeeper', 'Award-winning bookkeeper with 20+ years of experience managing financial records and accounting processes. Skilled in accounts payable, accounts receivable, reconciliations, payroll, and financial reporting. Known for accuracy, organization, confidentiality, and strong attention to detail. Dependable professional committed to maintaining accurate records and supporting smooth day-to-day financial operations.', 'https://overdriveaccountingservices.com/wp-content/uploads/2026/09/Karla-Gonzalez-1.png'],
  ['Shaun Hodo', 'In House Counsel', 'In-house counsel with nearly 10 years of experience advising a small business accounting firm. Well-versed in business law, including contracts, insurance, employment, and workers’ compensation. Experienced in contract review, legal risk management, negotiation, and general business matters. Provides strategic, practical legal guidance to protect the firm and support its continued growth.', 'https://overdriveaccountingservices.com/wp-content/uploads/2026/09/Shaun-Hodo-1.jpg'],
  ['Edgar Rosario', 'IT Lead / Developer - Ghostnet', 'Responsible for the website technology, deployment, security, and technical operations supporting the Overdrive Accounting Services demo.', null],
]

export default function AboutPage() {
  return <div className="about-page"><header className="resources-header"><a href="/" className="resources-brand"><img src="https://overdriveaccountingservices.com/wp-content/uploads/2024/05/WebLogo_White.png" alt="Overdrive Accounting Services" /></a><nav><a href="/">Home</a><a className="active" href="/about">About us</a><a href="/insights">Insights</a><a href="/faq">FAQ</a><a href="https://overdriveaccountingservices.securefilepro.com/portal/#/login">Client portal</a><a className="button button-small" href="/#appointment">Free consultation <ArrowUpRight size={15} /></a></nav></header><main><section className="about-page-hero"><div><span className="section-kicker">About us <span /></span><h1>The accounting partner <em>you deserve.</em></h1><a className="button button-accent" href="/#appointment">Schedule a free consultation <ArrowUpRight size={17} /></a></div><img src="https://overdriveaccountingservices.com/wp-content/uploads/2024/06/AboutUS.jpg" alt="Overdrive Accounting Services" /></section><section className="about-page-copy section-pad"><div className="section-kicker">Overdrive Accounting Services <span /></div><h2>Comprehensive financial services designed to drive your business’s success.</h2><p>Overdrive Accounting Services provides a comprehensive suite of financial services designed to drive your business’s success. From meticulous accounting and bookkeeping to expert payroll management, business advising, business plan creation, and small business funding application assistance, our team is dedicated to delivering professional and personalized solutions. We understand the challenges you face and are here to ensure your financial operations are seamless and your strategic decisions are informed. Let us help you navigate the complexities of financial management with precision and expertise. Contact us today to discover how Overdrive Accounting Services can elevate your business to new heights!</p></section><section className="leadership-section section-pad"><div className="section-kicker">Meet our leadership <span /></div><h2>The professionals behind <span>Overdrive.</span></h2><div className="leadership-grid">{team.map(([name, role, bio, image]) => <article className="leader-card" key={name}><div className="leader-image">{image ? <img src={image} alt={name} /> : <div className="leader-tech-mark"><MonitorCog size={74} strokeWidth={1.2} /></div>}</div><div className="leader-content"><h3>{name}</h3><span>{role}</span><p>{bio}</p></div></article>)}</div></section></main><footer className="resources-footer"><span>© 2024 Overdrive Accounting Services, LLC</span><a href="mailto:Info@OverdriveAccountingServices.com">Info@OverdriveAccountingServices.com</a></footer></div>
}
