import { useState } from 'react'
import { ArrowUpRight, ChevronDown } from 'lucide-react'

const faqs = [
  ['What Accounting Services Do You Offer?', 'We provide comprehensive accounting services including producing advanced financial statements, custom reporting, tax preparation, and compliance management. For a full list of accounting features and services available, please see our accounting page.'],
  ['Can You Handle Bookkeeping For A Small Business?', 'Absolutely, our bookkeeping services are tailored for businesses of all sizes, focusing on maintaining accurate and timely financial records that empower decision making for business owners.'],
  ['What Does Your Payroll Management Include?', 'Our payroll services include industry leading features including professional setup, processing, tax withholdings, filings, direct deposit, employee access, and so much more, all while ensuring compliance with all federal and state regulations. For a full list of payroll features and services available, please see our payroll page.'],
  ['How Can You Help With Business Advising?', 'With decades of experience on our staff, we offer business advising to help with financial planning, performance analysis, and strategic decision-making to improve efficiency and growth. Our philosophy is to bridge current industry standards with decades of experience.'],
  ['Can You Assist In Creating A Business Plan?', 'Yes, we help in drafting detailed business plans that include market analysis, organizational structure, financial projections, strategic objectives, and much more. Our experience in creating numerous business plans for clients seeking to work with the SBA and other lenders has provided invaluable experience to get the job done for companies of all sizes.'],
  ['How Do I Get Started With Your Services?', 'Give us a call at 352-749-2459 or schedule an initial consultation so we can discuss your needs and how we can assist.'],
  ['What Industries Do You Specialize In?', 'While we are equipped to handle clients from various industries, we have extensive experience with retail, services, construction, manufacturing, and technology sectors.'],
  ['How Often Will We Communicate About My Financial Status?', 'Communication frequency can be customized to your preferences. While all our clients have prescheduled monthly or quarterly meetings, we respond within 24 hours and provide timely updates and answers as needed.'],
  ['What Are Your Fees For Accounting Services?', 'Our fees vary based on the scope and complexity of the services required. We have multiple packages that provide for most business needs. For a full list of accounting features and services available, please see our Services page. Additional services may be available at either fixed-rate or hourly billing options.'],
  ['Are Your Services Compliant With The Latest Financial Regulations?', 'Yes, we stay updated with the latest financial regulations to ensure all your tax, accounting and payroll practices are compliant.'],
  ['Can You Integrate With My Existing Financial Software?', 'We can integrate with most major financial software platforms to ensure seamless data flow and reporting.'],
  ['How Do You Ensure The Confidentiality Of Our Financial Information?', 'We employ strict data security measures including encryption, secure storage, and confidentiality agreements with all staff.'],
  ['Do You Offer Digital Accounting Solutions?', 'Yes, we offer digital solutions including cloud-based accounting and electronic document management.'],
  ['Can Overdrive Accounting Services Help Reduce My Tax Liabilities?', 'We provide strategic tax planning to minimize liabilities and ensure you benefit from all available deductions and credits.'],
  ['How Can You Help If I’m Audited?', 'We offer audit support, which includes preparing all requested documentation and representing your business during the audit process.'],
  ['What Makes Overdrive Accounting Services Different From Other Firms?', 'Our business owner-focused approach allows us to be significantly more comprehensive and personalized as it is our only focus. Our commitment to client success sets us apart as it is not simply an annual transaction.'],
  ['Can You Manage Both Domestic And International Accounting?', 'Yes, we handle both domestic and international accounting requirements, including multi-currency transactions and reporting.'],
  ['What Is Your Experience With Financial Crisis Management?', 'We have extensive experience in helping businesses manage and recover from financial crises through careful planning and restructuring. Our focus is to be proactive and preventive minded for clients.'],
  ['How Quickly Can You Resolve Accounting Errors?', 'While uncommon for our tenured team we prioritize the resolution of any accounting errors, aiming to address them as quickly as possible, typically within 24 hours.'],
  ['What Is The Process For Business Plan Creation?', 'We start with a consultation to understand your business goals and needs, followed by market research and financial forecasting to create a comprehensive plan that meets SBA requirements.'],
  ['How Detailed Are The Financial Reports You Provide?', 'Our financial reports are detailed and can be customized to include key performance indicators relevant to your business sector.'],
  ['Can You Handle Multi-State Payroll?', 'Yes, we are equipped to manage payroll across multiple states, adhering to varying state tax laws and regulations.'],
  ['Do You Offer Part-Time CFO Services?', 'Yes, we offer part-time CFO services for businesses that need strategic financial leadership on a flexible basis.'],
  ['How Do You Charge For Business Advising Services?', 'Our business advising services are charged based on the complexity and duration of the consultancy, with both retainer and hourly options available. We provide multiple packages that provide options for business owners to decide which tier of service they need.'],
  ['How Can I Access My Financial Data?', 'We provide clients with access to their financial data through secure client portals that are accessible anytime.'],
]

export default function FaqPage() {
  const [open, setOpen] = useState(0)
  return <div className="faq-page"><header className="resources-header"><a href="/" className="resources-brand"><img src="https://overdriveaccountingservices.com/wp-content/uploads/2024/05/WebLogo_White.png" alt="Overdrive Accounting Services" /></a><nav><a href="/">Home</a><a href="/resources">Resources</a><a className="active" href="/faq">FAQ</a><a href="https://overdriveaccountingservices.securefilepro.com/portal/#/login">Client portal</a><a className="button button-small" href="/#appointment">Free consultation <ArrowUpRight size={15} /></a></nav></header><main className="faq-main"><div className="faq-hero"><span className="section-kicker">Overdrive Accounting Services</span><h1>Frequently asked <em>questions.</em></h1><p>Answers to common questions about our accounting, tax, payroll, business advisory, and financial services.</p></div><div className="faq-list">{faqs.map(([question, answer], index) => <article className={`faq-item ${open === index ? 'is-open' : ''}`} key={question}><button onClick={() => setOpen(open === index ? -1 : index)}><span>{question}</span><ChevronDown size={18} /></button>{open === index && <div className="faq-answer"><p>{answer}</p></div>}</article>)}</div><section className="faq-cta"><h2>Ready to get started?</h2><p>Schedule a free consultation so we can discuss your needs and how we can assist.</p><a className="button button-accent" href="/#appointment">Schedule a free consultation <ArrowUpRight size={17} /></a></section></main><footer className="resources-footer"><span>© 2024 Overdrive Accounting Services, LLC</span><a href="mailto:Info@OverdriveAccountingServices.com">Info@OverdriveAccountingServices.com</a></footer></div>
}
